version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Bearer token for authentication
      - AGENT_DRUGS_BEARER_TOKEN=${AGENT_DRUGS_BEARER_TOKEN}
      # Firebase project ID
      - FIREBASE_PROJECT_ID=agent-drugs
      # Service account credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      # Mount service account file
      - ./service-account.json:/app/service-account.json:ro
    stdin_open: true
    tty: true
    command: node dist/index.js
    networks:
      - agent-drugs

  # For local testing with Firebase emulators (optional)
  # firebase-emulators:
  #   image: node:20-alpine
  #   working_dir: /app
  #   command: npm run emulators
  #   ports:
  #     - "4000:4000"  # Emulator UI
  #     - "8080:8080"  # Cloud Functions
  #     - "9099:9099"  # Auth
  #     - "8081:8081"  # Firestore
  #   volumes:
  #     - .:/app
  #   networks:
  #     - agent-drugs

networks:
  agent-drugs:
    driver: bridge
