version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Firebase project ID
      - FIREBASE_PROJECT_ID=agent-drugs
      # Service account credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
      # Port for HTTP server
      - PORT=3000
      - NODE_ENV=development
    volumes:
      # Mount service account file (you need to download this from Firebase Console)
      - ./service-account.json:/app/service-account.json:ro
    ports:
      - "3000:3000"
    networks:
      - agent-drugs
    command: node dist/http-server.js

networks:
  agent-drugs:
    driver: bridge
